# Generated by Django 4.2 on 2023-04-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_customer_email'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
