# Generated by Django 4.2 on 2023-04-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_feedbacks_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='sent_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
