# Generated by Django 4.2 on 2023-04-04 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_customer_email'),
        ('contact', '0003_feedbacks_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='name',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer'),
        ),
    ]
