# Generated by Django 4.2 on 2023-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(default='', max_length=30)),
                ('published_at', models.TimeField(auto_now=True)),
                ('publisher_text', models.TextField(default='')),
                ('photo', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
