# Generated by Django 4.2 on 2023-04-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_publisher_name_blog_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='customer',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
