# Generated by Django 4.2 on 2023-04-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_customer_blog_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_at']},
        ),
    ]
