# Generated by Django 4.2 on 2023-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
