# Generated by Django 4.2 on 2023-04-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_chef_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
