# Generated by Django 4.2 on 2023-04-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_chef_restaurant_alter_chef_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='awards_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='happy_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pizza_branches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='addresse',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='working_hours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
