# Generated by Django 4.2 on 2023-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_awards_count_restaurant_happy_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isntagram_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
