# Generated by Django 4.2 on 2023-04-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_chef_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='working_since',
            field=models.TimeField(auto_now=True),
        ),
    ]
