# Generated by Django 4.2 on 2023-04-04 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_customerlogger_customer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLogger',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restaurant',
            field=models.ForeignKey(default='Restaurant.objects.first()', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
