# Generated by Django 4.2 on 2023-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='', upload_to='testImages/staff/%y/%m/%d'),
        ),
    ]
