# Generated by Django 4.2 on 2023-04-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='restaurant.restaurant'),
        ),
    ]
