# Generated by Django 4.2 on 2023-04-05 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_staff_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='awards',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='chefs', to='restaurant.restaurant'),
        ),
    ]
