# Generated by Django 4.2 on 2023-04-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='catigory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.catigory'),
        ),
    ]
