# Generated by Django 4.2 on 2023-04-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_is_hotmeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(default='', upload_to='testImages/%y/%m/%d'),
        ),
    ]
